/**
 * Server-side two-stage pipeline documentation and constants.
 *
 * This module documents how the WHATS'ON server processes native-format
 * reports using the two-stage pipeline defined in report definitions.
 *
 * ## Two-Stage Pipeline
 *
 * ### Stage 1: XSLT Transformation
 *   - Input: XML data from WHATS'ON query engine
 *   - Transform: XSLT stylesheet generated by XFEB
 *   - Processor: Saxon HE/PE/EE (server-side)
 *   - Output: XML fragment (e.g., xfeb:SheetFragment, xfeb:DocumentFragment)
 *
 * ### Stage 2: ZIP Assembly (Post-Processing)
 *   - Input: XML fragment from Stage 1 + template scaffold ZIP
 *   - Process: Parse fragment, merge into scaffold at injection target
 *   - Output: Complete document (.xlsx, .docx, .pptx, .ods, .odt)
 *
 * ## Report Definition PostProcessing Section
 *
 * When a report uses a native format, its report definition XML includes:
 *
 * ```xml
 * <PostProcessing required="true">
 *   <Stage>xslt-fragment</Stage>
 *   <TemplateScaffold>report-scaffold.zip</TemplateScaffold>
 *   <InjectionTarget>xl/worksheets/sheet1.xml</InjectionTarget>
 *   <OutputMimeType>application/vnd.openxmlformats-...</OutputMimeType>
 * </PostProcessing>
 * ```
 *
 * ## Server Implementation Notes
 *
 * The server should:
 * 1. Run Saxon on the XSLT with the XML data → produces XML fragment
 * 2. Read the scaffold ZIP from the report package
 * 3. Parse the XML fragment to extract the document-specific content
 * 4. Merge the extracted content into the scaffold at the injection target
 * 5. Output the assembled ZIP with the correct MIME type
 *
 * ## Fragment Namespaces
 *
 * Each format uses a unique namespace for its fragment wrapper:
 * - XLSX: urn:xfeb:spreadsheet-fragment:v1 (xfeb:SheetFragment)
 * - DOCX: urn:xfeb:document-fragment:v1 (xfeb:DocumentFragment)
 * - PPTX: urn:xfeb:slide-fragment:v1 (xfeb:SlideFragment)
 * - ODS/ODT: urn:xfeb:odf-fragment:v1 (xfeb:OdfFragment)
 */

/**
 * Saxon command-line examples for running Stage 1.
 */
export const SAXON_EXAMPLES = {
  xlsxNative: "java -jar saxon-he.jar -s:data.xml -xsl:report-transform.xslt -o:fragment.xml",
  docxNative: "java -jar saxon-he.jar -s:data.xml -xsl:report-transform.xslt -o:fragment.xml",
  pptxNative: "java -jar saxon-he.jar -s:data.xml -xsl:report-transform.xslt -o:fragment.xml",
  odsNative: "java -jar saxon-he.jar -s:data.xml -xsl:report-transform.xslt -o:fragment.xml",
  odtNative: "java -jar saxon-he.jar -s:data.xml -xsl:report-transform.xslt -o:fragment.xml",
} as const;

/**
 * Maps native format keys to their fragment root element local name.
 */
export const FRAGMENT_ROOT_ELEMENTS: Readonly<Record<string, string>> = {
  "xlsx-native": "SheetFragment",
  "docx-native": "DocumentFragment",
  "pptx-native": "SlideFragment",
  "ods-native": "OdfFragment",
  "odt-native": "OdfFragment",
};

/**
 * Maps native format keys to the scaffold ZIP entry that receives the merged content.
 */
export const INJECTION_TARGETS: Readonly<Record<string, string>> = {
  "xlsx-native": "xl/worksheets/sheet1.xml",
  "docx-native": "word/document.xml",
  "pptx-native": "ppt/slides/slide1.xml",
  "ods-native": "content.xml",
  "odt-native": "content.xml",
};
