import type { ColumnDefinition, StyleConfig } from "@/types";
import styles from "./PreviewTable.module.css";

interface PreviewTableProps {
  columns: readonly ColumnDefinition[];
  style: StyleConfig;
  groupBy: string | null;
  title: string;
}

/** Generate plausible mock value based on column format. */
function mockValue(col: ColumnDefinition, rowIndex: number): string {
  switch (col.format) {
    case "number":
      return String((rowIndex + 1) * 42 + rowIndex * 7);
    case "date":
      return `2025-0${rowIndex + 1}-${15 + rowIndex}`;
    case "datetime":
      return `2025-0${rowIndex + 1}-${15 + rowIndex}T${10 + rowIndex}:30:00`;
    case "text":
    case "auto":
    default:
      return `${col.header} ${rowIndex + 1}`;
  }
}

const MOCK_ROWS = [0, 1, 2] as const;

export function PreviewTable({ columns, style, groupBy, title }: PreviewTableProps) {
  if (columns.length === 0) {
    return (
      <div className={styles["container"]}>
        <div className={styles["empty"]}>Add columns to see a preview.</div>
      </div>
    );
  }

  const cellAlign = (align: ColumnDefinition["align"]): "left" | "center" | "right" =>
    align;

  return (
    <div className={styles["container"]} style={{ fontFamily: style.fontFamily, fontSize: style.fontSize }}>
      {style.showTitle && <div className={styles["title"]}>{title || "Untitled Report"}</div>}

      <div className={styles["tableWrap"]}>
        <table className={styles["table"]} role="table" aria-label="Preview">
          <thead>
            <tr>
              {columns.map((col) => (
                <th
                  key={col.id}
                  className={styles["headerCell"]}
                  style={{
                    backgroundColor: style.headerBg,
                    color: style.headerFg,
                    textAlign: cellAlign(col.align),
                    width: col.width > 0 ? `${col.width}px` : undefined,
                  }}
                >
                  {col.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {MOCK_ROWS.map((rowIndex) => (
              <PreviewRow
                key={rowIndex}
                columns={columns}
                rowIndex={rowIndex}
                style={style}
                groupBy={groupBy}
                cellAlign={cellAlign}
              />
            ))}
          </tbody>
        </table>
      </div>

      {style.showFooter && (
        <div className={styles["empty"]} style={{ fontSize: style.fontSize }}>
          Generated by Iksemel
        </div>
      )}
    </div>
  );
}

/* ─── PreviewRow sub-component ───────────────────────────────── */

interface PreviewRowProps {
  columns: readonly ColumnDefinition[];
  rowIndex: number;
  style: StyleConfig;
  groupBy: string | null;
  cellAlign: (align: ColumnDefinition["align"]) => "left" | "center" | "right";
}

function PreviewRow({ columns, rowIndex, style, groupBy, cellAlign }: PreviewRowProps) {
  const altBg = rowIndex % 2 === 1 ? style.altRowBg : undefined;
  const showGroup = groupBy && rowIndex === 0;

  return (
    <>
      {showGroup && (
        <tr className={styles["groupRow"]} style={{ backgroundColor: style.groupBg }}>
          <td className={styles["groupCell"]} colSpan={columns.length}>
            Group: Sample Group
          </td>
        </tr>
      )}
      <tr style={{ backgroundColor: altBg }}>
        {columns.map((col) => (
          <td
            key={col.id}
            className={styles["cell"]}
            style={{ textAlign: cellAlign(col.align) }}
          >
            {mockValue(col, rowIndex)}
          </td>
        ))}
      </tr>
    </>
  );
}
